### ISSUE TITLE
Promise function is called only once regardless of its arguments

### ISSUE THREAD

**Issue by apuchkov** [chrisronline/angular-promise-cache#10]
My problem is when I call function wrapped in promiseCache with different arguments I expect it to be executed once for every unique argument. I'm not if it is a bug or I don't use it incorrectly

Here's example: http://jsfiddle.net/apuchkov/7kcs10ef/

```
var myApp = angular.module('myApp', ['angular-promise-cache']);

myApp
    .factory('myAwesomeModel', function ($http, promiseCache) {
        return {
            getData: function (id) {
                return promiseCache({
                    args: [id],
                    promise: function (id) {
                        $('#log').append('<p>Making HTTP call for id: ' + id + '</p>')
                        return $http.get('/echo/json/');
                    }
                });
            }
        };
    })
    .controller('myAwesomeCtrl', function ($scope, myAwesomeModel) {
        myAwesomeModel.getData(1);
        myAwesomeModel.getData(1);
        myAwesomeModel.getData(2); // I expect a second http call here
        myAwesomeModel.getData(2);
    });
```

**Comment by chrisronline** [comment]
Hi @apuchkov 

Currently, the correct way to separate caches is by using the `key` parameter. In the example you posted above, one way would be to add a `key` argument to the `promiseCache({})` method that is unique based on the argument list - such as `key: 'pc_' + id`

**Comment by apuchkov** [comment]
Works well with the `key` argument. Thanks!
