### ISSUE TITLE
remove by key mask

### ISSUE THREAD

**Issue by dlebedynskyi** [chrisronline/angular-promise-cache#11]
one thing that probably should be good to add is ability to remove from cache by key mask like

``` 
return promiseCache({
                promise: function () {...                },
                key: "srv.getBy:" + args.toString(),
});

....
promiseCache.removeByMask(REGEX);
````

**Comment by chrisronline** [comment]
@dlebedynskyi Thanks for the suggestion. I've added in `v0.0.13`. Please let me know if this helps

**Comment by dlebedynskyi** [comment]
@chrisronline thanks will check after update
