### ISSUE TITLE
it's not caching data

### ISSUE THREAD

**Issue by caglarcem** [chrisronline/angular-promise-cache#12]
Hi there, thanks for great plugin.

I'm using promise cache to cache 'currentuser' for instance. 

First time I call it, it goes to the server, caches the promise and brings the data. The trouble is, it's going to the server each and every time I call it. It should be caching the resulting data I would've thought. What am I doing wrong?

app.factory('PromiseCacheFactory', function(Resource, promiseCache) {
    return {
        /* User */
        getUser: function(userId) {
            return promiseCache({
                key: 'user_' + userId,
                promise: function() {
                    return Resource.getUser(userId); // here goes $http call
                }
            });
        },

**Comment by chrisronline** [comment]
Hi @caglarcem!

Thanks for using the plugin!

Can you post more code snippets, including `Resource.getUser()` as well as the code calling this factory?

Thanks!

P.S. In the future, when posting code snippets, please use the [appropriate markdown](https://guides.github.com/features/mastering-markdown/) to make it easier to read. Thanks!

**Comment by caglarcem** [comment]
thanks for your response. so, it should cache the response data as well i take it?

here's http Resource

```javascript
app.factory('Resource', function($http) {
    return {
        /* User */
        getUser: function(userId) {
            return $http.get('/api/users/getById/' + userId);
        }
   }
});
```
...and promise cache factory consuming Resource

```javascript
app.factory('PromiseCacheFactory', function(Resource, promiseCache) {
    return {
        /* User */
        getUser: function(userId) {
            return promiseCache({
                key: 'user_' + userId,
                promise: function() {
                    return Resource.getUser(userId);
                }
            });
         }
     }
});
```
finally how cache factory is used

```javascript
var app = angular.module('hobCloudApp', [
    'angular-promise-cache'
]).config(['$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {

    $stateProvider
        .state('app-home', {
            url: '/home',
            templateUrl: '/views/partials/home.html',
            controller: 'HomeCtrl',
            resolve: {
                currentUser: function(Auth, PromiseCacheFactory, Encryption) {
                  return PromiseCacheFactory.getUser(Encryption.getUserIdFromToken(Auth.userToken)).then(function(response) {
                      return response.data;
                  });
                }
            },
        })
....
....
```

**Comment by chrisronline** [comment]
Hey @caglarcem 

I played around with your code and it seems to work fine. What might be tripping you up is the [default timeout](https://github.com/chrisronline/angular-promise-cache/blob/master/angular-promise-cache.js#L32)

To override this, pass in a `ttl` key in the creation of the promise cache object. Per the README, setting a value of `-1` will cause the key to never expire for that sesson (or if you're using local storage, until it's manually removed from there)

Does that make sense?

**Comment by caglarcem** [comment]
works fine now, thanks.

it doesn't really make sense that ttl default is so low and it's in milliseconds. It makes me think that perhaps data caching is not recommended or not for a long time. I understand that this is for caching promises rather than for data caching, but... Is it still a good practice what I'm doing, would you suggest using effective data caching as well or is it better to implement it myself / get another library for this specific purpose?

**Comment by chrisronline** [comment]
I think it's appropriate. The default TTL is set lower because it matched my use case at the time - in the original version, I didn't have long term storage support - just something cached in context of a single page load.

However, the library grew to support more long term data storage specifically around support for local storage. Nearly all other libraries will use local storage or some equivalent so I don't think you need to use another library - the caveat is that another library might offer some additional functionality or more granular control to some extent.

The main objective with this particular library is simplicity and "just works out of the box" mentality.

**Comment by caglarcem** [comment]
...and it does the job. Thanks for your time!

**Comment by caglarcem** [comment]
Hi Chris. There's another question I'd like to ask, although not closely related to this issue (maybe remotely), I commented here since I've already shared my code here. I didn't open an issue cuz I'm not sure if this is really an issue.

Now that I'm using the above code, I'm getting a user1 by userId1. When I try to access the same user again, it retrieves it from the cache and gets user1 for me. That's great.

But when I use the same call for a user2, with userId2, it still brings user1 instead and without going to the server. I had setup  cache key as "key: 'user_' + userId, " as you may see above. Since the keys are different, it should go for the other user I would've thought. Am I missing something, or is this key only for "// This is useful if you are creating different promises that need to share the same cache"  as documented?

**Comment by chrisronline** [comment]
Hey @caglarcem,

Are you using the local storage feature? Ensure those keys are different too. If not, please paste the code and I'll check it out.

Thanks,
Chris

**Comment by chrisronline** [comment]
Please open another issue if you're still experiencing issues.
