### ISSUE TITLE
Support for disabled storage

### ISSUE THREAD

**Issue by rolintoucour** [chrisronline/angular-promise-cache#14]
Hi,
Thanks for your work it is really usefull !

However today we noticed a problem with Chrome / Opera, in settings the user may disable the use of local data (avoid site from creating data), in the case this is totally crashing.

On line 36 :
ls = window.localStorage || {
          setItem: function() { },
          removeItem: function() { },
          getItem: function() { }
        },

The DOMException should only be caught to avoid troubles (exception is "VM1577:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.").

**Comment by chrisronline** [comment]
Thanks for the note! I'm a little behind on handling issues/PRs lately but I promise to get to this ASAP!

**Comment by chrisronline** [comment]
Fixed this in `v0.10`!
